### PR TITLE
Fix IPA code check

### PR DESCRIPTION
**Pull request by MdreW**
Test IPA code with curl and grep

**Solved issues**

- #42

**Tests**

- [ x] I manually tested

### CODE REVIEW

**Comment by peppelinux** [comment]
@MdreW I think it's time to merge this and have a new release

**Comment by MdreW** [comment]
Tomorrow I check if the request is still valid. In six months they may have updated the web API.

**Comment by MdreW** [comment]
I confirm, the code test still works fine. (it's an unofficial web API from the indicepa.gov.it  and can change)

I have another proposal: to add an alternative input mode for the script options. The environment parameters are perfect for the automation script but are not handy for manual operation.
I would like to add a params for add params from bash input.

Example for option select and text input:
```
if [[ -z $MD_ALG && ! -z $INTERACTIVE ]]; then
   PS3="Select algorith: "
   select MD_ALG in 'sha256' 'sha512'
   do
     break
   done
fi
if [ $(echo ${MD_ALG} | grep -c -P "^(sha256|sha512)$") -ne 1 ]; then
    echo "[E] MD_ALG must be one of [sha256, sha512], now ${MD_ALG}"
    exit 1
fi

if [[ -z $COMMON_NAME && ! -z $INTERACTIVE ]]; then
  if [ -z INTERACTIVE ]; then
    read -p 'COMMON_NAME: ' COMMON_NAME
  fi
fi
if [ $(echo ${COMMON_NAME} | grep -Pc "^\S(.*\S)?$") -ne 1 ]; then
    echo "[E] COMMON_NAME must be set"
    exit 1
fi
```

**Comment by peppelinux** [comment]
Consider me available to accept your PR

**Pull request merged**
